"""add content type balance check holdings to import jobs

Revision ID: 39bc2d1423f7
Revises: c524e0da4585
Create Date: 2026-06-08 09:22:01.127975+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39bc2d1423f7'
down_revision: Union[str, None] = 'c524e0da4585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_jobs', sa.Column('content_type', sa.String(length=20), nullable=True))
    op.add_column('import_jobs', sa.Column('balance_check', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('import_jobs', sa.Column('detected_holdings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_jobs', 'detected_holdings')
    op.drop_column('import_jobs', 'balance_check')
    op.drop_column('import_jobs', 'content_type')
    # ### end Alembic commands ###
